name: $(Date:yyyyMMdd)$(Rev:.r)

parameters:
    - buildConfiguration: Release

trigger:
  - master
  - develop
  - release/*
  - hotfix/*

pr:
  - develop
  - master
  - release/*
  - hotfix/*

resources:
  repositories:
    - repository: templates
      type: github
      name: CluedIn-io/AzurePipelines.Templates
      endpoint: 'CluedIn-io'

pool:
  vmImage: 'windows-latest'

variables:
  - group: nuget
  - name: testFolderPath
    value: '$(Build.SourcesDirectory)/test'
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: true
  - name: buildConfiguration
    value: ${{ parameters.buildConfiguration }}

steps:

  # Configure NuGet
- pwsh: |
    @('develop','release','AzurePipelines') | ForEach-Object{
        dotnet nuget update  source $_ -p $env:NUGET_KEY -u VssSessionToken --configfile nuget.config
    }
  condition: and(succeeded(), variables['nuget.key'])
  displayName: 'Add api token to access nuget artifacts'
  env:
    NUGET_KEY: $(nuget.key)

- template: crawler.netcore.build.yml@templates
