name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
  branches:
    include:
    - develop
    - master
    - release/*

pr:
  branches:
    include:
    - develop
    - master
    - release/*

resources:
  repositories:
    - repository: templates
      type: github
      name: CluedIn-io/AzurePipelines.Templates
      endpoint: 'CluedIn-io'
      ref: refs/heads/refactor

pool:
  vmImage: 'windows-latest'

variables:
  - name: testFolderPath
    value: '$(Build.SourcesDirectory)/test'
  - name: DOTNET_SKIP_FIRST_TIME_EXPERIENCE
    value: true
  - name: DOTNET_CLI_TELEMETRY_OPTOUT
    value: true
  - name: buildConfiguration
    value: Release

steps:

  - task: UseDotNet@2
    displayName: Install .NET SDK 6.0
    inputs:
      version: 6.0.x

  - task: UseDotNet@2
    displayName: Install .NET SDK 7.0
    inputs:
      # Pin version to prevent issue with output on solution build:
      # https://github.com/dotnet/sdk/issues/30625
      # We will have to update eventually, it's just by that time workaround might be available.
      version: 7.0.103

  # Configure NuGet
  - task: NuGetAuthenticate@0
    displayName: 'Authenticate with nuget'

  - template: crawler.build.yml@templates
